# Generated by Django 3.2.7 on 2021-09-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deals'),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('addres', models.CharField(max_length=255)),
                ('Deals', models.ManyToManyField(to='core.Deals')),
                ('Tag_Brand', models.ManyToManyField(to='core.Tag_Brand')),
            ],
        ),
    ]
